name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa os arquivos do repositório
      - uses: actions/checkout@v3

      # 2. Instala e configura o builder do Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
